import type { ZendeskProviderTicket } from "../types/zendesk.js";

function isoFromNow(daysOffset: number, hour: number, minute = 0) {
  const date = new Date();
  date.setDate(date.getDate() + daysOffset);
  date.setHours(hour, minute, 0, 0);
  return date.toISOString();
}

export function buildMockZendeskFixtureTickets(): ZendeskProviderTicket[] {
  return [
    {
      zendesk_ticket_id: "5001001",
      subject: "School portraits roster mismatch",
      requester_name: "Northview Elementary",
      requester_email: "office@northview.example.com",
      assignee_name: "Casey Support",
      assignee_id: "agent-1",
      organization_name: "Northview Elementary",
      group_name: "Schools Support",
      form_name: "Schools Request",
      status: "open",
      priority: "high",
      ticket_created_at: isoFromNow(-1, 8, 20),
      ticket_updated_at: isoFromNow(-1, 10, 35),
      ticket_solved_at: null,
      first_reply_minutes: 22,
      resolution_minutes: null,
      tags: ["schools", "roster", "picture_day"],
      external_url: "https://example.zendesk.com/agent/tickets/5001001",
      is_deleted: false,
      custom_fields: {},
      raw_payload: { fixture: true, queue: "schools" }
    },
    {
      zendesk_ticket_id: "5001002",
      subject: "Sports banner package arrived late",
      requester_name: "Lake Metro Athletics",
      requester_email: "ops@lakemetro.example.com",
      assignee_name: "Jordan Support",
      assignee_id: "agent-2",
      organization_name: "Lake Metro Athletics",
      group_name: "Sports Support",
      form_name: "Sports Request",
      status: "pending",
      priority: "normal",
      ticket_created_at: isoFromNow(-2, 9, 15),
      ticket_updated_at: isoFromNow(-1, 13, 5),
      ticket_solved_at: null,
      first_reply_minutes: 41,
      resolution_minutes: null,
      tags: ["sports", "delivery", "banner"],
      external_url: "https://example.zendesk.com/agent/tickets/5001002",
      is_deleted: false,
      custom_fields: {},
      raw_payload: { fixture: true, queue: "sports" }
    },
    {
      zendesk_ticket_id: "5001003",
      subject: "Picture day package never received",
      requester_name: "West Ridge Middle School",
      requester_email: "families@westridge.example.com",
      assignee_name: null,
      assignee_id: null,
      organization_name: "West Ridge Middle School",
      group_name: "Schools Support",
      form_name: "Schools Request",
      status: "new",
      priority: "urgent",
      ticket_created_at: isoFromNow(0, 7, 50),
      ticket_updated_at: isoFromNow(0, 7, 50),
      ticket_solved_at: null,
      first_reply_minutes: null,
      resolution_minutes: null,
      tags: ["schools", "package", "urgent"],
      external_url: "https://example.zendesk.com/agent/tickets/5001003",
      is_deleted: false,
      custom_fields: {},
      raw_payload: { fixture: true, queue: "schools" }
    },
    {
      zendesk_ticket_id: "5001004",
      subject: "Athletics order correction request",
      requester_name: "Prairie Sports Club",
      requester_email: "admin@prairiesports.example.com",
      assignee_name: "Jordan Support",
      assignee_id: "agent-2",
      organization_name: "Prairie Sports Club",
      group_name: "Sports Support",
      form_name: "Sports Request",
      status: "solved",
      priority: "normal",
      ticket_created_at: isoFromNow(-4, 11, 10),
      ticket_updated_at: isoFromNow(-2, 15, 45),
      ticket_solved_at: isoFromNow(-2, 15, 45),
      first_reply_minutes: 18,
      resolution_minutes: 1520,
      tags: ["sports", "order_change"],
      external_url: "https://example.zendesk.com/agent/tickets/5001004",
      is_deleted: false,
      custom_fields: {},
      raw_payload: { fixture: true, queue: "sports" }
    },
    {
      zendesk_ticket_id: "5001005",
      subject: "School makeup day confirmation",
      requester_name: "River Valley High",
      requester_email: "office@rivervalley.example.com",
      assignee_name: "Casey Support",
      assignee_id: "agent-1",
      organization_name: "River Valley High",
      group_name: "Schools Support",
      form_name: "Schools Request",
      status: "solved",
      priority: "low",
      ticket_created_at: isoFromNow(-6, 13, 25),
      ticket_updated_at: isoFromNow(-5, 16, 20),
      ticket_solved_at: isoFromNow(-5, 16, 20),
      first_reply_minutes: 12,
      resolution_minutes: 450,
      tags: ["schools", "reschedule"],
      external_url: "https://example.zendesk.com/agent/tickets/5001005",
      is_deleted: false,
      custom_fields: {},
      raw_payload: { fixture: true, queue: "schools" }
    },
    {
      zendesk_ticket_id: "5001006",
      subject: "General billing question",
      requester_name: "Parent Family",
      requester_email: "parent@example.com",
      assignee_name: "Taylor Finance",
      assignee_id: "agent-3",
      organization_name: null,
      group_name: "Customer Service",
      form_name: "Billing",
      status: "open",
      priority: "normal",
      ticket_created_at: isoFromNow(-3, 10, 0),
      ticket_updated_at: isoFromNow(-1, 9, 45),
      ticket_solved_at: null,
      first_reply_minutes: 33,
      resolution_minutes: null,
      tags: ["billing"],
      external_url: "https://example.zendesk.com/agent/tickets/5001006",
      is_deleted: false,
      custom_fields: {},
      raw_payload: { fixture: true, queue: "other" }
    },
    {
      zendesk_ticket_id: "5001007",
      subject: "Sports gallery access request",
      requester_name: "Metro Hoops Academy",
      requester_email: "manager@metrohoops.example.com",
      assignee_name: "Jordan Support",
      assignee_id: "agent-2",
      organization_name: "Metro Hoops Academy",
      group_name: "Sports Support",
      form_name: "Sports Request",
      status: "hold",
      priority: "normal",
      ticket_created_at: isoFromNow(-7, 14, 5),
      ticket_updated_at: isoFromNow(-2, 11, 30),
      ticket_solved_at: null,
      first_reply_minutes: 27,
      resolution_minutes: null,
      tags: ["sports", "gallery"],
      external_url: "https://example.zendesk.com/agent/tickets/5001007",
      is_deleted: false,
      custom_fields: {},
      raw_payload: { fixture: true, queue: "sports" }
    },
    {
      zendesk_ticket_id: "5001008",
      subject: "Picture day pricing clarification",
      requester_name: "Maple Grove School",
      requester_email: "pta@maplegrove.example.com",
      assignee_name: "Casey Support",
      assignee_id: "agent-1",
      organization_name: "Maple Grove School",
      group_name: "Schools Support",
      form_name: "Schools Request",
      status: "solved",
      priority: "normal",
      ticket_created_at: isoFromNow(-8, 9, 35),
      ticket_updated_at: isoFromNow(-7, 12, 50),
      ticket_solved_at: isoFromNow(-7, 12, 50),
      first_reply_minutes: 16,
      resolution_minutes: 310,
      tags: ["schools", "pricing"],
      external_url: "https://example.zendesk.com/agent/tickets/5001008",
      is_deleted: false,
      custom_fields: {},
      raw_payload: { fixture: true, queue: "schools" }
    },
    {
      zendesk_ticket_id: "5001009",
      subject: "Uncategorized request about print credits",
      requester_name: "Parent Family",
      requester_email: "credits@example.com",
      assignee_name: null,
      assignee_id: null,
      organization_name: null,
      group_name: "Customer Service",
      form_name: "General",
      status: "open",
      priority: "low",
      ticket_created_at: isoFromNow(-9, 15, 5),
      ticket_updated_at: isoFromNow(-3, 14, 25),
      ticket_solved_at: null,
      first_reply_minutes: 65,
      resolution_minutes: null,
      tags: ["credits"],
      external_url: "https://example.zendesk.com/agent/tickets/5001009",
      is_deleted: false,
      custom_fields: {},
      raw_payload: { fixture: true, queue: "other" }
    },
    {
      zendesk_ticket_id: "5001010",
      subject: "School image retake request",
      requester_name: "Birchwood Academy",
      requester_email: "retakes@birchwood.example.com",
      assignee_name: "Casey Support",
      assignee_id: "agent-1",
      organization_name: "Birchwood Academy",
      group_name: "Schools Support",
      form_name: "Schools Request",
      status: "solved",
      priority: "high",
      ticket_created_at: isoFromNow(-12, 8, 45),
      ticket_updated_at: isoFromNow(-11, 11, 10),
      ticket_solved_at: isoFromNow(-11, 11, 10),
      first_reply_minutes: 19,
      resolution_minutes: 520,
      tags: ["schools", "retake"],
      external_url: "https://example.zendesk.com/agent/tickets/5001010",
      is_deleted: false,
      custom_fields: {},
      raw_payload: { fixture: true, queue: "schools" }
    },
    {
      zendesk_ticket_id: "5001011",
      subject: "Sports order duplicate charge",
      requester_name: "West Metro Hockey",
      requester_email: "billing@westmetrohockey.example.com",
      assignee_name: "Taylor Finance",
      assignee_id: "agent-3",
      organization_name: "West Metro Hockey",
      group_name: "Sports Support",
      form_name: "Sports Request",
      status: "open",
      priority: "high",
      ticket_created_at: isoFromNow(-10, 16, 10),
      ticket_updated_at: isoFromNow(-1, 16, 30),
      ticket_solved_at: null,
      first_reply_minutes: 24,
      resolution_minutes: null,
      tags: ["sports", "billing"],
      external_url: "https://example.zendesk.com/agent/tickets/5001011",
      is_deleted: false,
      custom_fields: {},
      raw_payload: { fixture: true, queue: "sports" }
    },
    {
      zendesk_ticket_id: "5001012",
      subject: "School admin portal login issue",
      requester_name: "Southview District",
      requester_email: "support@southview.example.com",
      assignee_name: "Casey Support",
      assignee_id: "agent-1",
      organization_name: "Southview District",
      group_name: "Schools Support",
      form_name: "Schools Request",
      status: "solved",
      priority: "normal",
      ticket_created_at: isoFromNow(-15, 9, 0),
      ticket_updated_at: isoFromNow(-14, 10, 45),
      ticket_solved_at: isoFromNow(-14, 10, 45),
      first_reply_minutes: 10,
      resolution_minutes: 105,
      tags: ["schools", "portal"],
      external_url: "https://example.zendesk.com/agent/tickets/5001012",
      is_deleted: false,
      custom_fields: {},
      raw_payload: { fixture: true, queue: "schools" }
    },
    {
      zendesk_ticket_id: "5001013",
      subject: "Customer requested invoice copy",
      requester_name: "Parent Family",
      requester_email: "invoice@example.com",
      assignee_name: "Taylor Finance",
      assignee_id: "agent-3",
      organization_name: null,
      group_name: "Customer Service",
      form_name: "Billing",
      status: "solved",
      priority: "low",
      ticket_created_at: isoFromNow(-20, 11, 0),
      ticket_updated_at: isoFromNow(-19, 11, 45),
      ticket_solved_at: isoFromNow(-19, 11, 45),
      first_reply_minutes: 35,
      resolution_minutes: 280,
      tags: ["billing", "invoice"],
      external_url: "https://example.zendesk.com/agent/tickets/5001013",
      is_deleted: false,
      custom_fields: {},
      raw_payload: { fixture: true, queue: "other" }
    },
    {
      zendesk_ticket_id: "5001014",
      subject: "Athletics roster spelling correction",
      requester_name: "Capital City Track",
      requester_email: "coach@capitalcitytrack.example.com",
      assignee_name: "Jordan Support",
      assignee_id: "agent-2",
      organization_name: "Capital City Track",
      group_name: "Sports Support",
      form_name: "Sports Request",
      status: "solved",
      priority: "normal",
      ticket_created_at: isoFromNow(-25, 9, 15),
      ticket_updated_at: isoFromNow(-23, 8, 50),
      ticket_solved_at: isoFromNow(-23, 8, 50),
      first_reply_minutes: 29,
      resolution_minutes: 1320,
      tags: ["sports", "roster"],
      external_url: "https://example.zendesk.com/agent/tickets/5001014",
      is_deleted: false,
      custom_fields: {},
      raw_payload: { fixture: true, queue: "sports" }
    },
    {
      zendesk_ticket_id: "5001015",
      subject: "General customer question about shipping timeline",
      requester_name: "Parent Family",
      requester_email: "shipping@example.com",
      assignee_name: "Taylor Finance",
      assignee_id: "agent-3",
      organization_name: null,
      group_name: "Customer Service",
      form_name: "General",
      status: "solved",
      priority: "normal",
      ticket_created_at: isoFromNow(-29, 13, 40),
      ticket_updated_at: isoFromNow(-28, 15, 15),
      ticket_solved_at: isoFromNow(-28, 15, 15),
      first_reply_minutes: 47,
      resolution_minutes: 330,
      tags: ["shipping"],
      external_url: "https://example.zendesk.com/agent/tickets/5001015",
      is_deleted: false,
      custom_fields: {},
      raw_payload: { fixture: true, queue: "other" }
    }
  ];
}
